// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFdsjjrn2hSni6y06-Lq-gANh2mh3LfM',
    appId: '1:388927170984:web:a33781b3ea13e0fb90d59d',
    messagingSenderId: '388927170984',
    projectId: 'test-pro-ebdf1',
    authDomain: 'test-pro-ebdf1.firebaseapp.com',
    storageBucket: 'test-pro-ebdf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB93GProJOBrB2e3tyJ64Ij4BgDp-aoHY',
    appId: '1:388927170984:android:9055c8b37da94e9d90d59d',
    messagingSenderId: '388927170984',
    projectId: 'test-pro-ebdf1',
    storageBucket: 'test-pro-ebdf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk0QogrVFKwNWNzzKIRTYdeyuUexfBcPk',
    appId: '1:388927170984:ios:6c50ad606585c3bc90d59d',
    messagingSenderId: '388927170984',
    projectId: 'test-pro-ebdf1',
    storageBucket: 'test-pro-ebdf1.appspot.com',
    iosClientId: '388927170984-7poqurg8gbaid4j1c6qqt70it025u80p.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPro',
  );
}
